import hashlib
import logging
import os
import pickle
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import sparse


logger = logging.getLogger("cinimatch.loader")
BASE_DIR = Path(__file__).resolve().parent
DEFAULT_DATA_DIR = BASE_DIR / "data"


@dataclass(frozen=True)
class MovieCatalog:
    df: pd.DataFrame
    movie_vectors: np.ndarray
    movie_ids: list[str]
    title_to_index: dict[str, int]
    id_to_index: dict[str, int]
    data_dir: Path
    dataset_sha256: str


def normalize_text(value) -> str:
    return value.lower().strip() if isinstance(value, str) else ""


def split_set(value) -> set[str]:
    return {part.strip().lower() for part in str(value).split(",") if part.strip()}


def _artifact_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _load_pickle(path: Path):
    # These artifacts are generated by the local training/data pipeline. Keep them
    # outside Git and only mount trusted, checksummed files in deployed systems.
    with path.open("rb") as handle:
        return pickle.load(handle)


def _required_file(data_dir: Path, name: str) -> Path:
    path = data_dir / name
    if not path.exists():
        raise FileNotFoundError(
            f"Required data file is missing: {path}. "
            "Place the movie dataset and vector artifacts in backend/data."
        )
    return path


def _json_safe(frame: pd.DataFrame) -> pd.DataFrame:
    frame = frame.replace([np.inf, -np.inf], np.nan)

    for col in frame.select_dtypes(include=["object", "string"]).columns:
        frame[col] = frame[col].fillna("")

    for col in frame.select_dtypes(include=["float", "int"]).columns:
        frame[col] = frame[col].fillna(0)

    return frame.where(pd.notnull(frame), None)


def _rating_series(frame: pd.DataFrame) -> pd.Series:
    tmdb = pd.to_numeric(frame.get("vote_average", 0), errors="coerce").fillna(0)
    imdb = pd.to_numeric(frame.get("rating", 0), errors="coerce").fillna(0)
    return tmdb.where(tmdb > 0, imdb)


def _votes_series(frame: pd.DataFrame) -> pd.Series:
    tmdb = pd.to_numeric(frame.get("vote_count", 0), errors="coerce").fillna(0)
    imdb = pd.to_numeric(frame.get("votes", 0), errors="coerce").fillna(0)
    return tmdb.where(tmdb > 0, imdb)


def _prepare_movies(frame: pd.DataFrame) -> pd.DataFrame:
    result = _json_safe(frame.copy())
    result["_title_norm"] = result.get("title", "").astype(str).str.lower().str.strip()
    result["_rating_score"] = _rating_series(result)
    result["_votes_score"] = _votes_series(result)
    result["_popularity_score"] = pd.to_numeric(
        result.get("popularity", 0), errors="coerce"
    ).fillna(0)
    result["_year_score"] = pd.to_numeric(result.get("year", 0), errors="coerce").fillna(0)

    if "genres" in result.columns:
        result["_genre_set"] = result["genres"].apply(split_set)
    else:
        result["_genre_set"] = [set() for _ in range(len(result))]

    if "cast" in result.columns:
        result["_cast_set"] = result["cast"].apply(split_set)

    if "directors" in result.columns:
        result["_director_norm"] = result["directors"].apply(normalize_text)

    return result


def _normalize_vectors(vectors):
    if sparse.issparse(vectors):
        matrix = vectors.tocsr().astype(np.float32)
        norms = np.sqrt(matrix.multiply(matrix).sum(axis=1)).A1
        norms[norms == 0] = 1
        return matrix.multiply(1 / norms[:, np.newaxis]).tocsr()

    matrix = np.asarray(vectors, dtype=np.float32)
    norms = np.linalg.norm(matrix, axis=1, keepdims=True)
    norms[norms == 0] = 1
    return matrix / norms


@lru_cache(maxsize=1)
def load_catalog(data_dir: str | None = None) -> MovieCatalog:
    resolved_dir = Path(data_dir or os.getenv("DATA_DIR", DEFAULT_DATA_DIR)).resolve()
    dataset_path = _required_file(resolved_dir, "rich_movies_dataset.csv")
    vectors_path = _required_file(resolved_dir, "movie_vectors.pkl")
    ids_path = _required_file(resolved_dir, "movie_ids.pkl")
    title_map_path = _required_file(resolved_dir, "title_to_index.pkl")

    logger.info("Loading movie catalog from %s", resolved_dir)
    frame = _prepare_movies(pd.read_csv(dataset_path))
    vectors = _normalize_vectors(_load_pickle(vectors_path))
    movie_ids = list(_load_pickle(ids_path))
    title_to_index = {
        normalize_text(title): int(index)
        for title, index in dict(_load_pickle(title_map_path)).items()
        if normalize_text(title)
    }

    vector_count = vectors.shape[0]
    if len(frame) != vector_count or len(movie_ids) != vector_count:
        raise ValueError(
            "Movie dataset, vector matrix, and movie ID list must have matching lengths."
        )

    catalog = MovieCatalog(
        df=frame,
        movie_vectors=vectors,
        movie_ids=movie_ids,
        title_to_index=title_to_index,
        id_to_index={movie_id: i for i, movie_id in enumerate(movie_ids)},
        data_dir=resolved_dir,
        dataset_sha256=_artifact_sha256(dataset_path),
    )
    logger.info("Loaded %s movies and %s vectors", len(frame), vector_count)
    return catalog
